import re

with open('/home/lib/oer_chatbot_project/TLCN_OER_Lakehouse/scripts/moodle_seed_data.php', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    # General categories and course
    "Khoa Cong nghe Thong tin": "Khoa Công nghệ Thông tin",
    "Truong Dai hoc Su pham Ky thuat TP.HCM (HCMUTE) – 01 Vo Van Ngan, P.Linh Chieu, TP.Thu Duc": "Trường Đại học Công nghệ Kỹ thuật TP.HCM (HCMUTE) – 01 Võ Văn Ngân, P.Linh Chiểu, TP.Thủ Đức",
    "Nam nhat – Co so Dai cuong": "Năm nhất – Cơ sở Đại cương",
    "Nam hai – Co so Nganh": "Năm hai – Cơ sở Ngành",
    "Nam ba – Chuyen nganh": "Năm ba – Chuyên ngành",
    "Sinh vien CNTT K22": "Sinh viên CNTT K22",
    "Dinh huong: Ky thuat phan mem": "Định hướng: Kỹ thuật phần mềm",
    "Dinh huong: AI/ML va Khoa hoc du lieu": "Định hướng: AI/ML và Khoa học dữ liệu",
    "Thong bao va Hoi dap": "Thông báo và Hỏi đáp",
    "Noi trao doi thac mac.": "Nơi trao đổi thắc mắc.",
    "De cuong chi tiet Mon hoc": "Đề cương chi tiết Môn học",
    "Doc truoc de cuong chi tiet truoc khi bat dau mon hoc.": "Đọc trước đề cương chi tiết trước khi bắt đầu môn học.",

    # C/C++
    "Ma mon hoc:": "Mã môn học:",
    "So tin chi:": "Số tín chỉ:",
    "Hoc ky:": "Học kỳ:",
    "Nam nhat": "Năm nhất",
    "Nam hai": "Năm hai",
    "Nam ba": "Năm ba",
    "Mon hoc cung cap kien thuc co ban ve lap trinh": "Môn học cung cấp kiến thức cơ bản về lập trình",
    "thuat toan, kieu du lieu, cau truc dieu khien": "thuật toán, kiểu dữ liệu, cấu trúc điều khiển",
    "ham, mang, con tro, va kieu du lieu cau truc": "hàm, mảng, con trỏ, và kiểu dữ liệu cấu trúc",
    "Ngon ngu su dung chinh la C/C++": "Ngôn ngữ sử dụng chính là C/C++",
    "Giang vien:": "Giảng viên:",
    "Cong cu:": "Công cụ:",
    "Phan mem:": "Phần mềm:",
    "Tuan 1: Tong quan ve may tinh va lap trinh": "Tuần 1: Tổng quan về máy tính và lập trình",
    "Khai niem may tinh, phan cung, phan mem; Gioi thieu ngon ngu C/C++; Moi truong lap trinh (IDE); Chuong trinh C dau tien; Quy trinh bien dich va thuc thi.": "Khái niệm máy tính, phần cứng, phần mềm; Giới thiệu ngôn ngữ C/C++; Môi trường lập trình (IDE); Chương trình C đầu tiên; Quy trình biên dịch và thực thi.",
    "Tuan 2: Kieu du lieu, bien, hang va toan tu": "Tuần 2: Kiểu dữ liệu, biến, hằng và toán tử",
    "Cac kieu du lieu co ban (int, float, char); Khai bao bien, hang; Cac toan tu so hoc, quan he, logic; Bieu thuc va thu tu uu tien; Nhap xuat du lieu co ban (cin, cout).": "Các kiểu dữ liệu cơ bản (int, float, char); Khai báo biến, hằng; Các toán tử số học, quan hệ, logic; Biểu thức và thứ tự ưu tiên; Nhập xuất dữ liệu cơ bản (cin, cout).",
    "Tuan 3: Cau truc dieu khien re nhanh": "Tuần 3: Cấu trúc điều khiển rẽ nhánh",
    "Cau truc if, if-else, if-else if; Cau truc switch-case; Toan tu dieu kien (? :); Bai tap ung dung: Giai phuong trinh bac 1, 2, kien tra nam nhuan.": "Cấu trúc if, if-else, if-else if; Cấu trúc switch-case; Toán tử điều kiện (? :); Bài tập ứng dụng: Giải phương trình bậc 1, 2, kiểm tra năm nhuận.",
    "Tuan 4: Cau truc lap (Phan 1)": "Tuần 4: Cấu trúc lặp (Phần 1)",
    "Vong lap while; Vong lap do-while; Vong lap for; Cach chon vong lap phu hop; Cac loi thuong gap voi vong lap (lap vo han).": "Vòng lặp while; Vòng lặp do-while; Vòng lặp for; Cách chọn vòng lặp phù hợp; Các lỗi thường gặp với vòng lặp (lặp vô hạn).",
    "Tuan 5: Cau truc lap (Phan 2)": "Tuần 5: Cấu trúc lặp (Phần 2)",
    "Lenh break, continue; Vong lap long nhau; Bai tap ung dung: Ve hinh bang dau sao, tinh tong day so, kiem tra so nguyen to.": "Lệnh break, continue; Vòng lặp lồng nhau; Bài tập ứng dụng: Vẽ hình bằng dấu sao, tính tổng dãy số, kiểm tra số nguyên tố.",
    "Tuan 6: Ham (Function)": "Tuần 6: Hàm (Function)",
    "Khai niem va loi ich cua ham; Khai bao va dinh nghia ham; Truyen tham tri, truyen tham chieu; Pham vi bien (cuc bo, toan cuc); Ham de quy (co ban).": "Khái niệm và lợi ích của hàm; Khai báo và định nghĩa hàm; Truyền tham trị, truyền tham chiếu; Phạm vi biến (cục bộ, toàn cục); Hàm đệ quy (cơ bản).",
    "Tuan 7: Mang 1 chieu": "Tuần 7: Mảng 1 chiều",
    "Khai niem mang; Khai bao, khoi tao mang 1 chieu; Duyet mang; Tim kiem co ban tren mang (tuyen tinh); Cac bai tap tim max, min, tinh tong mang.": "Khái niệm mảng; Khai báo, khởi tạo mảng 1 chiều; Duyệt mảng; Tìm kiếm cơ bản trên mảng (tuyến tính); Các bài tập tìm max, min, tính tổng mảng.",
    "Tuan 8: KIEM TRA GIUA KY": "Tuần 8: KIỂM TRA GIỮA KỲ",
    "Noi dung:": "Nội dung:",
    "Hinh thuc:": "Hình thức:",
    "Tu kieu du lieu den mang 1 chieu": "Từ kiểu dữ liệu đến mảng 1 chiều",
    "Thuc hanh tren may 90 phut": "Thực hành trên máy 90 phút",
    "Tuan 9: Thuat toan sap xep co ban tren mang": "Tuần 9: Thuật toán sắp xếp cơ bản trên mảng",
    "Bubble Sort (Sap xep noi bot); Selection Sort (Sap xep chon); Insertion Sort (Sap xep chen); So sanh do phuc tap cua cac thuat toan.": "Bubble Sort (Sắp xếp nổi bọt); Selection Sort (Sắp xếp chọn); Insertion Sort (Sắp xếp chèn); So sánh độ phức tạp của các thuật toán.",
    "Tuan 10: Mang 2 chieu (Ma tran)": "Tuần 10: Mảng 2 chiều (Ma trận)",
    "Khai bao va khoi tao mang 2 chieu; Duyet mang 2 chieu; Cac phep toan ma tran: Cong, Nhan ma tran, Ma tran chuyen vi.": "Khai báo và khởi tạo mảng 2 chiều; Duyệt mảng 2 chiều; Các phép toán ma trận: Cộng, Nhân ma trận, Ma trận chuyển vị.",
    "Tuan 11: Chuoi ky tu (String)": "Tuần 11: Chuỗi ký tự (String)",
    "Chuoi C-style (mang char); Thu vien string.h; Nhap xuat chuoi co khoang trang; Thu vien chuoi C++ (std::string); Cac bai tap xu ly chuoi.": "Chuỗi C-style (mảng char); Thư viện string.h; Nhập xuất chuỗi có khoảng trắng; Thư viện chuỗi C++ (std::string); Các bài tập xử lý chuỗi.",
    "Tuan 12: Con tro (Phan 1)": "Tuần 12: Con trỏ (Phần 1)",
    "Khai niem bo nho va dia chi; Con tro la gi?; Khai bao va khoi tao con tro; Toan tu & va *; Moi quan he giua con tro va mang 1 chieu.": "Khái niệm bộ nhớ và địa chỉ; Con trỏ là gì?; Khai báo và khởi tạo con trỏ; Toán tử & và *; Mối quan hệ giữa con trỏ và mảng 1 chiều.",
    "Tuan 13: Con tro (Phan 2) va Cap phat dong": "Tuần 13: Con trỏ (Phần 2) và Cấp phát động",
    "Con tro cap 2; Bo nho Heap vs Stack; Cap phat bo nho dong: malloc, free (C) va new, delete (C++); Con tro ham (gioi thieu).": "Con trỏ cấp 2; Bộ nhớ Heap vs Stack; Cấp phát bộ nhớ động: malloc, free (C) và new, delete (C++); Con trỏ hàm (giới thiệu).",
    "Tuan 14: Kieu du lieu cau truc (Struct)": "Tuần 14: Kiểu dữ liệu cấu trúc (Struct)",
    "Dinh nghia Struct; Truy xuat cac thanh vien cua Struct; Mang Struct (quan ly danh sach sinh vien); Con tro Struct.": "Định nghĩa Struct; Truy xuất các thành viên của Struct; Mảng Struct (quản lý danh sách sinh viên); Con trỏ Struct.",
    "Tuan 15: THI CUOI KY": "Tuần 15: THI CUỐI KỲ",
    "Toan bo kien thuc da hoc, trong tam vao Mang, Chuoi, Con tro va Struct.": "Toàn bộ kiến thức đã học, trọng tâm vào Mảng, Chuỗi, Con trỏ và Struct.",

    # TRRTT501
    "Mon hoc nghien cuu cac kien thuc toan hoc lam nen tang cho khoa hoc may tinh": "Môn học nghiên cứu các kiến thức toán học làm nền tảng cho khoa học máy tính",
    "logic, tap hop, ly thuyet do thi, dai so Boole, va cac ky thuat dem.": "logic, tập hợp, lý thuyết đồ thị, đại số Boole, và các kỹ thuật đếm.",
    "Tuan 1: Logic menh de": "Tuần 1: Logic mệnh đề",
    "Menh de la gi? Cac phep toan logic (AND, OR, NOT, XOR, Keo theo, Tuong duong); Bang chan tri; Cac luat logic; Chung minh tuong duong logic.": "Mệnh đề là gì? Các phép toán logic (AND, OR, NOT, XOR, Kéo theo, Tương đương); Bảng chân trị; Các luật logic; Chứng minh tương đương logic.",
    "Tuan 2: Logic vi tu": "Tuần 2: Logic vị từ",
    "Vi tu va luong tu (Voi moi, Ton tai); Phu dinh cua luong tu; Luong tu long nhau; Lap luan hop le va cac nguyen tac suy luan (Modus Ponens, Modus Tollens).": "Vị từ và lượng từ (Với mọi, Tồn tại); Phủ định của lượng từ; Lượng từ lồng nhau; Lập luận hợp lệ và các nguyên tắc suy luận (Modus Ponens, Modus Tollens).",
    "Tuan 3: Tap hop": "Tuần 3: Tập hợp",
    "Khai niem tap hop; Cac phep toan tren tap hop (Giao, Hop, Hieu, Phan bu); Tap luy thua; Tuong duong giua Tap hop va Logic menh de.": "Khái niệm tập hợp; Các phép toán trên tập hợp (Giao, Hợp, Hiệu, Phần bù); Tập lũy thừa; Tương đương giữa Tập hợp và Logic mệnh đề.",
    "Tuan 4: Ham so va Phep toan": "Tuần 4: Hàm số và Phép toán",
    "Ham so (Toan anh, Don anh, Song anh); Ham nguoc; Ham hop; Day so; Cap so cong, Cap so nhan.": "Hàm số (Toàn ánh, Đơn ánh, Song ánh); Hàm ngược; Hàm hợp; Dãy số; Cấp số cộng, Cấp số nhân.",
    "Tuan 5: Ky thuat dem co ban": "Tuần 5: Kỹ thuật đếm cơ bản",
    "Quy tac cong, Quy tac nhan; Nguyen ly bu tru (Inclusion-Exclusion Principle); Nguyen ly chuong bồ câu (Pigeonhole Principle).": "Quy tắc cộng, Quy tắc nhân; Nguyên lý bù trừ (Inclusion-Exclusion Principle); Nguyên lý chuồng bồ câu (Pigeonhole Principle).",
    "Tuan 6: Hoan vi va To hop": "Tuần 6: Hoán vị và Tổ hợp",
    "Hoan vi khong lap; Chinh hop khong lap; To hop khong lap; Hoan vi/To hop co lap; Nhi thuc Newton.": "Hoán vị không lặp; Chỉnh hợp không lặp; Tổ hợp không lặp; Hoán vị/Tổ hợp có lặp; Nhị thức Newton.",
    "Tuan 7: He thuc de quy": "Tuần 7: Hệ thức đệ quy",
    "Day Fibonacci; Giai he thuc de quy tuyen tinh he so hang (bac 1, bac 2); Ung dung he thuc de quy trong thuat toan.": "Dãy Fibonacci; Giải hệ thức đệ quy tuyến tính hệ số hằng (bậc 1, bậc 2); Ứng dụng hệ thức đệ quy trong thuật toán.",
    "Logic, Tap hop, Ky thuat dem, De quy": "Logic, Tập hợp, Kỹ thuật đếm, Đệ quy",
    "Thi viet tu luan 60 phut": "Thi viết tự luận 60 phút",
    "Tuan 9: Quan he (Relations)": "Tuần 9: Quan hệ (Relations)",
    "Tich Descartes; Quan he hai ngoi; Cac tinh chat (Phan xa, Doi xung, Phan doi xung, Bac cau); Quan he tuong duong va Phan hoach; Quan he thu tu bo phan.": "Tích Descartes; Quan hệ hai ngôi; Các tính chất (Phản xạ, Đối xứng, Phản đối xứng, Bắc cầu); Quan hệ tương đương và Phân hoạch; Quan hệ thứ tự bộ phận.",
    "Tuan 10: Dai so Boole (Boolean Algebra)": "Tuần 10: Đại số Boole (Boolean Algebra)",
    "Dinh nghia dai so Boole; Cac ham Boole; Bieu dien ham Boole bang tong cac tich (SOP) va tich cac tong (POS); Bieu do Karnaugh (K-map) de toi thieu hoa ham Boole.": "Định nghĩa đại số Boole; Các hàm Boole; Biểu diễn hàm Boole bằng tổng các tích (SOP) và tích các tổng (POS); Biểu đồ Karnaugh (K-map) để tối thiểu hóa hàm Boole.",
    "Tuan 11: Ly thuyet Do thi - Co ban": "Tuần 11: Lý thuyết Đồ thị - Cơ bản",
    "Do thi vo huong, co huong; Bac cua dinh; Duong di, Chu trinh; Tinh lien thong; Do thi vo huong lien thong; Do thi co huong lien thong manh/yeu.": "Đồ thị vô hướng, có hướng; Bậc của đỉnh; Đường đi, Chu trình; Tính liên thông; Đồ thị vô hướng liên thông; Đồ thị có hướng liên thông mạnh/yếu.",
    "Tuan 12: Do thi dac biet va Bieu dien do thi": "Tuần 12: Đồ thị đặc biệt và Biểu diễn đồ thị",
    "Do thi day du (Kn), Do thi hai phia (Bipartite Graph); Bieu dien do thi bang ma tran ke, ma tran trong so, danh sach ke.": "Đồ thị đầy đủ (Kn), Đồ thị hai phía (Bipartite Graph); Biểu diễn đồ thị bằng ma trận kề, ma trận trọng số, danh sách kề.",
    "Tuan 13: Duong di Euler va Hamilton": "Tuần 13: Đường đi Euler và Hamilton",
    "Dinh ly Euler ve duong di va chu trinh Euler; Bai toan 7 cay cau Konigsberg; Duong di va chu trinh Hamilton; Bai toan Nguoi ban hang (TSP).": "Định lý Euler về đường đi và chu trình Euler; Bài toán 7 cây cầu Konigsberg; Đường đi và chu trình Hamilton; Bài toán Người bán hàng (TSP).",
    "Tuan 14: Cay (Trees)": "Tuần 14: Cây (Trees)",
    "Dinh nghia va tinh chat cua Cay; Cay co re; Cay nhi phan; Cay bao trum (Spanning tree); Thuat toan Kruskal va Prim tim cay khung nho nhat.": "Định nghĩa và tính chất của Cây; Cây có rễ; Cây nhị phân; Cây bao trùm (Spanning tree); Thuật toán Kruskal và Prim tìm cây khung nhỏ nhất.",
    "Quan he, Dai so Boole, Ly thuyet do thi, Cay.": "Quan hệ, Đại số Boole, Lý thuyết đồ thị, Cây.",

    # Java
    "Mon hoc gioi thieu phuong phap lap trinh huong doi tuong (OOP) su dung ngon ngu Java. Sinh vien se hieu cac tinh chat": "Môn học giới thiệu phương pháp lập trình hướng đối tượng (OOP) sử dụng ngôn ngữ Java. Sinh viên sẽ hiểu các tính chất",
    "Dong goi, Ke thua, Da hinh, Truu tuong va ap dung cac Design Pattern co ban.": "Đóng gói, Kế thừa, Đa hình, Trừu tượng và áp dụng các Design Pattern cơ bản.",
    "Tuan 1: Tong quan OOP va Java": "Tuần 1: Tổng quan OOP và Java",
    "Giai thich OOP la gi; So sanh Lap trinh thu tuc (C) va OOP (Java); Cai dat JDK, IntelliJ IDEA/Eclipse; Kien truc JVM, JRE, JDK; Chuong trinh Java dau tien (Hello World).": "Giải thích OOP là gì; So sánh Lập trình thủ tục (C) và OOP (Java); Cài đặt JDK, IntelliJ IDEA/Eclipse; Kiến trúc JVM, JRE, JDK; Chương trình Java đầu tiên (Hello World).",
    "Tuan 2: Java co ban": "Tuần 2: Java cơ bản",
    "Kieu du lieu nguyen thuy va kieu doi tuong (Wrapper classes); String trong Java (String Pool, StringBuilder); Toan tu, Cau truc re nhanh, Cau truc lap; Nhap/Xuat co ban voi Scanner.": "Kiểu dữ liệu nguyên thủy và kiểu đối tượng (Wrapper classes); String trong Java (String Pool, StringBuilder); Toán tử, Cấu trúc rẽ nhánh, Cấu trúc lặp; Nhập/Xuất cơ bản với Scanner.",
    "Tuan 3: Class va Object": "Tuần 3: Class và Object",
    "Dinh nghia Lop (Class) va Doi tuong (Object); Thuoc tinh (Fields) va Phuong thuc (Methods); Constructor (mac dinh va co tham so); Tu khoa 'this'; Garbage Collection trong Java.": "Định nghĩa Lớp (Class) và Đối tượng (Object); Thuộc tính (Fields) và Phương thức (Methods); Constructor (mặc định và có tham số); Từ khóa 'this'; Garbage Collection trong Java.",
    "Tuan 4: Tinh Dong goi (Encapsulation)": "Tuần 4: Tính Đóng gói (Encapsulation)",
    "Access Modifiers (private, default, protected, public); Getter va Setter; Data hiding; Tu khoa static va final; Khoi tao static block.": "Access Modifiers (private, default, protected, public); Getter và Setter; Data hiding; Từ khóa static và final; Khởi tạo static block.",
    "Tuan 5: Tinh Ke thua (Inheritance)": "Tuần 5: Tính Kế thừa (Inheritance)",
    "Khai niem ke thua; Tu khoa 'extends' va 'super'; Method Overriding (Ghi de phuong thuc); So sanh Overloading vs Overriding; Class Object (lop cha cua moi lop).": "Khái niệm kế thừa; Từ khóa 'extends' và 'super'; Method Overriding (Ghi đè phương thức); So sánh Overloading vs Overriding; Class Object (lớp cha của mọi lớp).",
    "Tuan 6: Tinh Da hinh (Polymorphism)": "Tuần 6: Tính Đa hình (Polymorphism)",
    "Da hinh thoi gian bien dich (Compile-time) va Da hinh thoi gian chay (Run-time); Upcasting va Downcasting; Tu khoa 'instanceof'; Bai tap ap dung Da hinh quan ly nhan vien.": "Đa hình thời gian biên dịch (Compile-time) và Đa hình thời gian chạy (Run-time); Upcasting và Downcasting; Từ khóa 'instanceof'; Bài tập áp dụng Đa hình quản lý nhân viên.",
    "Tuan 7: Tinh Truu tuong (Abstraction)": "Tuần 7: Tính Trừu tượng (Abstraction)",
    "Abstract Class: Khai bao, dac diem, khi nao su dung; Interface: Khai bao, tu khoa 'implements', Multiple inheritance thong qua Interface; So sanh Abstract Class vs Interface (Java 8+ default methods).": "Abstract Class: Khai báo, đặc điểm, khi nào sử dụng; Interface: Khai báo, từ khóa 'implements', Multiple inheritance thông qua Interface; So sánh Abstract Class vs Interface (Java 8+ default methods).",
    "4 tinh chat OOP, Abstract Class, Interface": "4 tính chất OOP, Abstract Class, Interface",
    "Thuc hanh code Java 90 phut tren may": "Thực hành code Java 90 phút trên máy",
    "Tuan 9: Xu ly Ngoai le (Exception Handling)": "Tuần 9: Xử lý Ngoại lệ (Exception Handling)",
    "Checked Exception vs Unchecked Exception; Khoi try-catch-finally; Tu khoa 'throw' va 'throws'; Tu tao Custom Exception; Best practices trong xu ly loi.": "Checked Exception vs Unchecked Exception; Khối try-catch-finally; Từ khóa 'throw' và 'throws'; Tự tạo Custom Exception; Best practices trong xử lý lỗi.",
    "Tuan 10: Java Collections Framework": "Tuần 10: Java Collections Framework",
    "Gioi thieu Generics; List (ArrayList, LinkedList); Set (HashSet, TreeSet); Map (HashMap, TreeMap); Iterator va Enhanced for-loop; Lop tien ich Collections (sort, binarySearch).": "Giới thiệu Generics; List (ArrayList, LinkedList); Set (HashSet, TreeSet); Map (HashMap, TreeMap); Iterator và Enhanced for-loop; Lớp tiện ích Collections (sort, binarySearch).",
    "Tuan 11: File I/O trong Java": "Tuần 11: File I/O trong Java",
    "Byte Stream (InputStream, OutputStream); Character Stream (Reader, Writer); BufferedReader va BufferedWriter; Doc/Ghi Object (Serialization); Thao tac voi File bang java.nio.file.": "Byte Stream (InputStream, OutputStream); Character Stream (Reader, Writer); BufferedReader và BufferedWriter; Đọc/Ghi Object (Serialization); Thao tác với File bằng java.nio.file.",
    "Tuan 12: Da luong (Multithreading)": "Tuần 12: Đa luồng (Multithreading)",
    "Thread vs Process; Tao Thread bang cach extend lop Thread hoac implement giao dien Runnable; Vong doi cua Thread; Dong bo hoa (Synchronization, tu khoa synchronized); Deadlock.": "Thread vs Process; Tạo Thread bằng cách extend lớp Thread hoặc implement giao diện Runnable; Vòng đời của Thread; Đồng bộ hóa (Synchronization, từ khóa synchronized); Deadlock.",
    "Tuan 13: Giao dien nguoi dung (GUI) voi JavaFX": "Tuần 13: Giao diện người dùng (GUI) với JavaFX",
    "Gioi thieu JavaFX (thay the Swing); Stage, Scene, Nodes; Layouts (VBox, HBox, GridPane...); Xu ly su kien (Event Handling) voi Button, TextField.": "Giới thiệu JavaFX (thay thế Swing); Stage, Scene, Nodes; Layouts (VBox, HBox, GridPane...); Xử lý sự kiện (Event Handling) với Button, TextField.",
    "Tuan 14: Design Patterns co ban": "Tuần 14: Design Patterns cơ bản",
    "Singleton Pattern; Factory Method Pattern; Observer Pattern; Ap dung MVC (Model-View-Controller) trong JavaFX.": "Singleton Pattern; Factory Method Pattern; Observer Pattern; Áp dụng MVC (Model-View-Controller) trong JavaFX.",
    "Toan bo kien thuc, tap trung nang cao, OOP, Collections, File I/O": "Toàn bộ kiến thức, tập trung nâng cao, OOP, Collections, File I/O",

    # CTDL
    "Mon hoc quan trong nhat cua nganh CNTT. Sinh vien hoc cach to chuc du lieu hieu qua va cac thuat toan": "Môn học quan trọng nhất của ngành CNTT. Sinh viên học cách tổ chức dữ liệu hiệu quả và các thuật toán",
    "tim kiem, sap xep, do thi. Ngon ngu cai dat thuong la C++ hoac Java.": "tìm kiếm, sắp xếp, đồ thị. Ngôn ngữ cài đặt thường là C++ hoặc Java.",
    "Tuan 1: Tong quan ve Thuat toan & Do phuc tap": "Tuần 1: Tổng quan về Thuật toán & Độ phức tạp",
    "Khai niem CTDL va Giai thuat; Danh gia do phuc tap thoi gian (Time Complexity); Ky hieu Big O, Big Omega, Big Theta; Cach tinh do phuc tap cua vong lap, vong lap long nhau.": "Khái niệm CTDL và Giải thuật; Đánh giá độ phức tạp thời gian (Time Complexity); Ký hiệu Big O, Big Omega, Big Theta; Cách tính độ phức tạp của vòng lặp, vòng lặp lồng nhau.",
    "Tuan 2: Mang va Danh sach lien ket": "Tuần 2: Mảng và Danh sách liên kết",
    "Mang (Array) - uu nhuoc diem; Danh sach lien ket don (Singly Linked List): Node, them/xoa vao dau, cuoi, giua; Danh sach lien ket doi (Doubly Linked List); Danh sach lien ket vong.": "Mảng (Array) - ưu nhược điểm; Danh sách liên kết đơn (Singly Linked List): Node, thêm/xóa vào đầu, cuối, giữa; Danh sách liên kết đôi (Doubly Linked List); Danh sách liên kết vòng.",
    "Tuan 3: Ngan xep (Stack)": "Tuần 3: Ngăn xếp (Stack)",
    "Khai niem LIFO (Last In First Out); Cai dat Stack bang Mang va Linked List; Ung dung: Kiem tra ngoac don hop le, Tinh toan bieu thuc hau to (Postfix), Undo/Redo.": "Khái niệm LIFO (Last In First Out); Cài đặt Stack bằng Mảng và Linked List; Ứng dụng: Kiểm tra ngoặc đơn hợp lệ, Tính toán biểu thức hậu tố (Postfix), Undo/Redo.",
    "Tuan 4: Hang doi (Queue)": "Tuần 4: Hàng đợi (Queue)",
    "Khai niem FIFO (First In First Out); Cai dat Queue bang Mang (Circular Queue) va Linked List; Priority Queue (Hang doi uu tien); Ung dung: Dat lich CPU, xu ly request.": "Khái niệm FIFO (First In First Out); Cài đặt Queue bằng Mảng (Circular Queue) và Linked List; Priority Queue (Hàng đợi ưu tiên); Ứng dụng: Đặt lịch CPU, xử lý request.",
    "Tuan 5: De quy va Quay lui": "Tuần 5: Đệ quy và Quay lui",
    "Tu duy de quy; Master Theorem (Dinh ly tho) de tinh do phuc tap; Thuat toan Quay lui (Backtracking); Bai toan: N-Queens, Sudoku, Sinh hoan vi.": "Tư duy đệ quy; Master Theorem (Định lý thợ) để tính độ phức tạp; Thuật toán Quay lui (Backtracking); Bài toán: N-Queens, Sudoku, Sinh hoán vị.",
    "Tuan 6: Thuat toan Sap xep (Sorting)": "Tuần 6: Thuật toán Sắp xếp (Sorting)",
    "On tap Selection, Insertion, Bubble Sort; Divide and Conquer (Chia de tri); Merge Sort: Thuat toan va do phuc tap O(N log N); Quick Sort: Chon Pivot, phan hoach (Partition).": "Ôn tập Selection, Insertion, Bubble Sort; Divide and Conquer (Chia để trị); Merge Sort: Thuật toán và độ phức tạp O(N log N); Quick Sort: Chọn Pivot, phân hoạch (Partition).",
    "Tuan 7: Thuat toan Tim kiem (Searching)": "Tuần 7: Thuật toán Tìm kiếm (Searching)",
    "Tim kiem tuyen tinh (Linear Search); Tim kiem nhi phan (Binary Search); Ung dung cua Tim kiem nhi phan tren khong gian ket qua; Tim kiem noi suy (Interpolation Search).": "Tìm kiếm tuyến tính (Linear Search); Tìm kiếm nhị phân (Binary Search); Ứng dụng của Tìm kiếm nhị phân trên không gian kết quả; Tìm kiếm nội suy (Interpolation Search).",
    "Big O, Array, Linked List, Stack, Queue, Recursion, Sorting, Searching": "Big O, Array, Linked List, Stack, Queue, Recursion, Sorting, Searching",
    "Tuan 9: Cay (Tree) va Cay nhi phan": "Tuần 9: Cây (Tree) và Cây nhị phân",
    "Khai niem Cay; Cay nhi phan (Binary Tree); Duyet cay: Pre-order, In-order, Post-order, Level-order (BFS); Cay bieu thuc.": "Khái niệm Cây; Cây nhị phân (Binary Tree); Duyệt cây: Pre-order, In-order, Post-order, Level-order (BFS); Cây biểu thức.",
    "Tuan 10: Cay nhi phan tim kiem (BST)": "Tuần 10: Cây nhị phân tìm kiếm (BST)",
    "Tinh chat BST; Thao tac: Tim kiem, Them, Xoa node tren BST; Truong hop toi nhat cua BST (Cay lech); Gioi thieu AVL Tree (Cay can bang).": "Tính chất BST; Thao tác: Tìm kiếm, Thêm, Xóa node trên BST; Trường hợp tồi nhất của BST (Cây lệch); Giới thiệu AVL Tree (Cây cân bằng).",
    "Tuan 11: Heaps": "Tuần 11: Heaps",
    "Khai niem Min-Heap, Max-Heap; Bieu dien Heap bang Mang; Thao tac Insert, Extract-Min/Max; Thuat toan Heap Sort; Su dung Heap cho Priority Queue.": "Khái niệm Min-Heap, Max-Heap; Biểu diễn Heap bằng Mảng; Thao tác Insert, Extract-Min/Max; Thuật toán Heap Sort; Sử dụng Heap cho Priority Queue.",
    "Tuan 12: Bang bam (Hash Table)": "Tuần 12: Bảng băm (Hash Table)",
    "Hash Function (Ham bam); Collisions (Dung do); Cach xu ly dung do: Chaining (Danh sach lien ket), Open Addressing (Linear Probing, Quadratic Probing).": "Hash Function (Hàm băm); Collisions (Đụng độ); Cách xử lý đụng độ: Chaining (Danh sách liên kết), Open Addressing (Linear Probing, Quadratic Probing).",
    "Tuan 13: Do thi (Graph) - Bieu dien va Duyet": "Tuần 13: Đồ thị (Graph) - Biểu diễn và Duyệt",
    "Bieu dien Do thi: Ma tran ke, Danh sach ke; Duyet BFS (Tim duong di ngan nhat tren do thi khong trong so); Duyet DFS (Kiem tra chu trinh, Topological Sort).": "Biểu diễn Đồ thị: Ma trận kề, Danh sách kề; Duyệt BFS (Tìm đường đi ngắn nhất trên đồ thị không trọng số); Duyệt DFS (Kiểm tra chu trình, Topological Sort).",
    "Tuan 14: Thuat toan Do thi (Duong di ngan nhat & MST)": "Tuần 14: Thuật toán Đồ thị (Đường đi ngắn nhất & MST)",
    "Duong di ngan nhat (Shortest Path): Thuat toan Dijkstra (O(E log V)), Thuat toan Bellman-Ford; Cay khung nho nhat (MST): Prim va Kruskal bang Disjoint Set (Union-Find).": "Đường đi ngắn nhất (Shortest Path): Thuật toán Dijkstra (O(E log V)), Thuật toán Bellman-Ford; Cây khung nhỏ nhất (MST): Prim và Kruskal bằng Disjoint Set (Union-Find).",
    "Trees, Heap, Hash Table, Graph.": "Trees, Heap, Hash Table, Graph.",

    # CSDL
    "Mon hoc cung cap kien thuc ly thuyet va thuc hanh ve thiet ke, xay dung va quan tri co so du lieu quan he.": "Môn học cung cấp kiến thức lý thuyết và thực hành về thiết kế, xây dựng và quản trị cơ sở dữ liệu quan hệ.",
    "Sinh vien su dung MySQL/SQL Server, hieu nguyen tac ACID, va co nen tang de hoc ORM, NoSQL sau nay.": "Sinh viên sử dụng MySQL/SQL Server, hiểu nguyên tắc ACID, và có nền tảng để học ORM, NoSQL sau này.",
    "Tuan 1: Tong quan CSDL – Mo hinh du lieu": "Tuần 1: Tổng quan CSDL – Mô hình dữ liệu",
    "CSDL la gi? DBMS va RDBMS; Mo hinh phang (Flat File) vs Mo hinh quan he; Cac loai DBMS: MySQL, PostgreSQL, Oracle, SQL Server; Cai dat MySQL 8 + MySQL Workbench; Tao CSDL va bang dau tien.": "CSDL là gì? DBMS và RDBMS; Mô hình phẳng (Flat File) vs Mô hình quan hệ; Các loại DBMS: MySQL, PostgreSQL, Oracle, SQL Server; Cài đặt MySQL 8 + MySQL Workbench; Tạo CSDL và bảng đầu tiên.",
    "Tuan 2: Mo hinh Thuc the – Ket hop (ER Model)": "Tuần 2: Mô hình Thực thể – Kết hợp (ER Model)",
    "Thuc the (Entity) va Thuoc tinh (Attribute); Khoa chinh (PK) va Khoa ngoai (FK); Quan he (Relationship): 1-1, 1-N, N-M; Ky hieu ER Diagram (Chen va Crow\\'s Foot); Chuyen doi ER sang luoc do quan he; Bai tap: Ve ER cho he thong quan ly sinh vien.": "Thực thể (Entity) và Thuộc tính (Attribute); Khóa chính (PK) và Khóa ngoại (FK); Quan hệ (Relationship): 1-1, 1-N, N-M; Ký hiệu ER Diagram (Chen và Crow\\'s Foot); Chuyển đổi ER sang lược đồ quan hệ; Bài tập: Vẽ ER cho hệ thống quản lý sinh viên.",
    "Tuan 3: SQL DDL – Tao va Quan ly Bang": "Tuần 3: SQL DDL – Tạo và Quản lý Bảng",
    "CREATE DATABASE, USE; CREATE TABLE voi cac rang buoc: NOT NULL, UNIQUE, PRIMARY KEY, FOREIGN KEY, DEFAULT, CHECK; ALTER TABLE: them/xoa/sua cot, rang buoc; DROP TABLE, TRUNCATE; Kieu du lieu MySQL: INT, VARCHAR, TEXT, DATETIME, DECIMAL, ENUM.": "CREATE DATABASE, USE; CREATE TABLE với các ràng buộc: NOT NULL, UNIQUE, PRIMARY KEY, FOREIGN KEY, DEFAULT, CHECK; ALTER TABLE: thêm/xóa/sửa cột, ràng buộc; DROP TABLE, TRUNCATE; Kiểu dữ liệu MySQL: INT, VARCHAR, TEXT, DATETIME, DECIMAL, ENUM.",
    "Tuan 4: SQL DML – Thao tac Du lieu": "Tuần 4: SQL DML – Thao tác Dữ liệu",
    "INSERT INTO: them 1 hang, nhieu hang; SELECT: lay du lieu co dieu kien (WHERE), sap xep (ORDER BY), gioi han (LIMIT, OFFSET); UPDATE: cap nhat co dieu kien; DELETE: xoa co dieu kien; DISTINCT; Alias (AS).": "INSERT INTO: thêm 1 hàng, nhiều hàng; SELECT: lấy dữ liệu có điều kiện (WHERE), sắp xếp (ORDER BY), giới hạn (LIMIT, OFFSET); UPDATE: cập nhật có điều kiện; DELETE: xóa có điều kiện; DISTINCT; Alias (AS).",
    "Tuan 5: Truy van nang cao – JOIN": "Tuần 5: Truy vấn nâng cao – JOIN",
    "INNER JOIN: giao giua 2 bang; LEFT/RIGHT OUTER JOIN; FULL OUTER JOIN (dung UNION); SELF JOIN; Cross Join; Subquery: trong WHERE, trong FROM, Correlated Subquery; EXISTS va NOT EXISTS; UNION, INTERSECT, EXCEPT.": "INNER JOIN: giao giữa 2 bảng; LEFT/RIGHT OUTER JOIN; FULL OUTER JOIN (dùng UNION); SELF JOIN; Cross Join; Subquery: trong WHERE, trong FROM, Correlated Subquery; EXISTS và NOT EXISTS; UNION, INTERSECT, EXCEPT.",
    "Tuan 6: Ham tong hop va Nhom hoa": "Tuần 6: Hàm tổng hợp và Nhóm hóa",
    "Ham tong hop: COUNT, SUM, AVG, MIN, MAX; GROUP BY: nhom theo mot hay nhieu cot; HAVING: loc sau nhom (khac WHERE); Window Function (MySQL 8+): ROW_NUMBER, RANK, DENSE_RANK, LEAD, LAG, SUM OVER PARTITION BY; Bai tap thong ke ban hang.": "Hàm tổng hợp: COUNT, SUM, AVG, MIN, MAX; GROUP BY: nhóm theo một hay nhiều cột; HAVING: lọc sau nhóm (khác WHERE); Window Function (MySQL 8+): ROW_NUMBER, RANK, DENSE_RANK, LEAD, LAG, SUM OVER PARTITION BY; Bài tập thống kê bán hàng.",
    "Tuan 7: Chuan hoa CSDL": "Tuần 7: Chuẩn hóa CSDL",
    "Phu thuoc ham (Functional Dependency); 1NF: Bo nhom lap; 2NF: Bo phu thuoc ham mot phan; 3NF: Bo phu thuoc ham bac cau; BCNF: Truong hop dac biet 3NF; 4NF: Phu thuoc da tri; Bai tap chuan hoa he thong dat hang truc tuyen.": "Phụ thuộc hàm (Functional Dependency); 1NF: Bỏ nhóm lặp; 2NF: Bỏ phụ thuộc hàm một phần; 3NF: Bỏ phụ thuộc hàm bắc cầu; BCNF: Trường hợp đặc biệt 3NF; 4NF: Phụ thuộc đa trị; Bài tập chuẩn hóa hệ thống đặt hàng trực tuyến.",
    "ER Model, DDL, DML, JOIN, Subquery, Chuan hoa.": "ER Model, DDL, DML, JOIN, Subquery, Chuẩn hóa.",
    "Thuc hanh tren may 90 phut – viet cac truy van SQL theo de bai thuc te.": "Thực hành trên máy 90 phút – viết các truy vấn SQL theo đề bài thực tế.",
    "Tuan 9: View, Stored Procedure, Function": "Tuần 9: View, Stored Procedure, Function",
    "View: Tao, su dung, cap nhat; Stored Procedure: IN/OUT parameter, bien, dieu kien, vong lap; User-Defined Function (Scalar, Table-Valued); So sanh SP vs Function; Ung dung: SP quan ly dat ve, SP tinh tien dien.": "View: Tạo, sử dụng, cập nhật; Stored Procedure: IN/OUT parameter, biến, điều kiện, vòng lặp; User-Defined Function (Scalar, Table-Valued); So sánh SP vs Function; Ứng dụng: SP quản lý đặt vé, SP tính tiền điện.",
    "Tuan 10: Trigger va Cursor": "Tuần 10: Trigger và Cursor",
    "Trigger: BEFORE/AFTER INSERT, UPDATE, DELETE; NEW va OLD values; Ung dung Trigger: Kiem tra toan ven du lieu phuc tap, Ghi log (Audit trail); Cursor: Khai bao, mo, duyet tung dong, dong cursor.": "Trigger: BEFORE/AFTER INSERT, UPDATE, DELETE; NEW và OLD values; Ứng dụng Trigger: Kiểm tra toàn vẹn dữ liệu phức tạp, Ghi log (Audit trail); Cursor: Khai báo, mở, duyệt từng dòng, đóng cursor.",
    "Tuan 11: Transaction va Dong thoi (Concurrency)": "Tuần 11: Transaction và Đồng thời (Concurrency)",
    "Transaction la gi? Tinh chat ACID (Atomicity, Consistency, Isolation, Durability); COMMIT va ROLLBACK; Cac van de dong thoi: Dirty Read, Non-repeatable Read, Phantom Read; Cac muc co lap (Isolation Levels).": "Transaction là gì? Tính chất ACID (Atomicity, Consistency, Isolation, Durability); COMMIT và ROLLBACK; Các vấn đề đồng thời: Dirty Read, Non-repeatable Read, Phantom Read; Các mức cô lập (Isolation Levels).",
    "Tuan 12: Chi muc (Indexing) va Toi uu cau truy van": "Tuần 12: Chỉ mục (Indexing) và Tối ưu câu truy vấn",
    "Chi muc la gi? B-Tree va Hash Index; Clustered vs Non-clustered Index; Khi nao nen/khong nen dung chi muc; Lenh EXPLAIN; Cac nguyen tac toi uu hoa SQL (tranh SELECT *, dung JOIN thay vi Subquery, Indexing cot dung trong WHERE).": "Chỉ mục là gì? B-Tree và Hash Index; Clustered vs Non-clustered Index; Khi nào nên/không nên dùng chỉ mục; Lệnh EXPLAIN; Các nguyên tắc tối ưu hóa SQL (tránh SELECT *, dùng JOIN thay vì Subquery, Indexing cột dùng trong WHERE).",
    "Tuan 13: Quan tri CSDL va Bao mat": "Tuần 13: Quản trị CSDL và Bảo mật",
    "Quan ly User va Quyen (GRANT, REVOKE); Backup va Restore (Logical backup voi mysqldump, Physical backup); SQL Injection va cach phong chong.": "Quản lý User và Quyền (GRANT, REVOKE); Backup và Restore (Logical backup với mysqldump, Physical backup); SQL Injection và cách phòng chống.",
    "Tuan 14: Gioi thieu NoSQL": "Tuần 14: Giới thiệu NoSQL",
    "Gioi han cua RDBMS khi scale; Khai niem NoSQL; Phan loai NoSQL: Document (MongoDB), Key-Value (Redis), Column-family (Cassandra), Graph (Neo4j); CAP Theorem; MongoDB co ban: CRUD tren JSON.": "Giới hạn của RDBMS khi scale; Khái niệm NoSQL; Phân loại NoSQL: Document (MongoDB), Key-Value (Redis), Column-family (Cassandra), Graph (Neo4j); CAP Theorem; MongoDB cơ bản: CRUD trên JSON.",
    "Bao ve do an cuoi ky: Xay dung He thong CSDL hoan chinh": "Bảo vệ đồ án cuối kỳ: Xây dựng Hệ thống CSDL hoàn chỉnh",

    # OS
    "Mon hoc gioi thieu kien thuc cot loi ve cach He dieu hanh hoat dong:": "Môn học giới thiệu kiến thức cốt lõi về cách Hệ điều hành hoạt động:",
    "quan ly tien trinh, dong bo hoa, quan ly bo nho va he thong tap tin. Thuc hanh tren moi truong Linux bang C.": "quản lý tiến trình, đồng bộ hóa, quản lý bộ nhớ và hệ thống tập tin. Thực hành trên môi trường Linux bằng C.",
    "Tuan 1: Tong quan ve He dieu hanh": "Tuần 1: Tổng quan về Hệ điều hành",
    "Chuc nang cua HDH; Lich su phat trien (Mainframe, Batch, Time-sharing, PC, Mobile); Kien truc HDH (Monolithic, Microkernel); System Calls la gi? Cach HDH giao tiep voi phan cung.": "Chức năng của HDH; Lịch sử phát triển (Mainframe, Batch, Time-sharing, PC, Mobile); Kiến trúc HDH (Monolithic, Microkernel); System Calls là gì? Cách HDH giao tiếp với phần cứng.",
    "Tuan 2: Quan ly Tien trinh (Process Management)": "Tuần 2: Quản lý Tiến trình (Process Management)",
    "Tien trinh la gi? Trang thai tien trinh (New, Ready, Running, Waiting, Terminated); Khoi dieu khien tien trinh (PCB); Context Switch; Tao tien trinh moi: fork() trong Linux.": "Tiến trình là gì? Trạng thái tiến trình (New, Ready, Running, Waiting, Terminated); Khối điều khiển tiến trình (PCB); Context Switch; Tạo tiến trình mới: fork() trong Linux.",
    "Tuan 3: Lap lich CPU (CPU Scheduling)": "Tuần 3: Lập lịch CPU (CPU Scheduling)",
    "Bo lap lich: Short-term, Medium-term, Long-term; Cac tieu chi lap lich (Turnaround time, Waiting time, Response time); Cac thuat toan lap lich: FCFS, SJF (Preemptive/Non-preemptive), Priority, Round Robin.": "Bộ lập lịch: Short-term, Medium-term, Long-term; Các tiêu chí lập lịch (Turnaround time, Waiting time, Response time); Các thuật toán lập lịch: FCFS, SJF (Preemptive/Non-preemptive), Priority, Round Robin.",
    "Tuan 4: Da luong (Multithreading OS level)": "Tuần 4: Đa luồng (Multithreading OS level)",
    "Luong (Thread) vs Tien trinh (Process); User threads vs Kernel threads; Da luong trong Linux (Pthreads); Loi ich cua da luong (Responsiveness, Resource sharing).": "Luồng (Thread) vs Tiến trình (Process); User threads vs Kernel threads; Đa luồng trong Linux (Pthreads); Lợi ích của đa luồng (Responsiveness, Resource sharing).",
    "Tuan 5: Dong bo hoa Tien trinh (Synchronization) I": "Tuần 5: Đồng bộ hóa Tiến trình (Synchronization) I",
    "Race condition (Tranh chap du lieu); Mien gang (Critical Section); Giai phap phan mem: Thuat toan Peterson\\'s Solution; Giai phap phan cung: TestAndSet, CompareAndSwap.": "Race condition (Tranh chấp dữ liệu); Miền găng (Critical Section); Giải pháp phần mềm: Thuật toán Peterson\\'s Solution; Giải pháp phần cứng: TestAndSet, CompareAndSwap.",
    "Tuan 6: Dong bo hoa Tien trinh II": "Tuần 6: Đồng bộ hóa Tiến trình II",
    "Mutex Locks; Semaphores (Counting va Binary); Cac bai toan dong bo kinh dien: Bounded-Buffer (Producer-Consumer), Readers-Writers, Dining-Philosophers.": "Mutex Locks; Semaphores (Counting và Binary); Các bài toán đồng bộ kinh điển: Bounded-Buffer (Producer-Consumer), Readers-Writers, Dining-Philosophers.",
    "Tuan 7: Tac nghen (Deadlock)": "Tuần 7: Tắc nghẽn (Deadlock)",
    "Dieu kien xay ra Deadlock (Mutual exclusion, Hold and wait, No preemption, Circular wait); Do thi cap phat tai nguyen; Phong tranh Deadlock (Banker\\'s Algorithm); Phat hien va phuc hoi Deadlock.": "Điều kiện xảy ra Deadlock (Mutual exclusion, Hold and wait, No preemption, Circular wait); Đồ thị cấp phát tài nguyên; Phòng tránh Deadlock (Banker\\'s Algorithm); Phát hiện và phục hồi Deadlock.",
    "Process, Scheduling, Threads, Synchronization, Deadlock.": "Process, Scheduling, Threads, Synchronization, Deadlock.",
    "Tuan 9: Quan ly Bo nho (Memory Management) I": "Tuần 9: Quản lý Bộ nhớ (Memory Management) I",
    "Khong gian dia chi logic vs physical; Memory Management Unit (MMU); Cap phat bo nho lien tuc (Contiguous Allocation: First-fit, Best-fit, Worst-fit); Phan manh ngoai va phan manh trong.": "Không gian địa chỉ logic vs physical; Memory Management Unit (MMU); Cấp phát bộ nhớ liên tục (Contiguous Allocation: First-fit, Best-fit, Worst-fit); Phân mảnh ngoài và phân mảnh trong.",
    "Tuan 10: Quan ly Bo nho II - Phan trang (Paging)": "Tuần 10: Quản lý Bộ nhớ II - Phân trang (Paging)",
    "Khai niem Phan trang (Paging) de giai quyet phan manh ngoai; Page Table; Translation Look-aside Buffer (TLB); Phan doan (Segmentation); Ket hop Paging va Segmentation.": "Khái niệm Phân trang (Paging) để giải quyết phân mảnh ngoài; Page Table; Translation Look-aside Buffer (TLB); Phân đoạn (Segmentation); Kết hợp Paging và Segmentation.",
    "Tuan 11: Bo nho ao (Virtual Memory)": "Tuần 11: Bộ nhớ ảo (Virtual Memory)",
    "Khai niem bo nho ao; Demand Paging; Loi trang (Page Fault); Cac thuat toan thay the trang (Page Replacement Algorithms): FIFO, Optimal, LRU (Least Recently Used), Clock; Thrashing la gi?": "Khái niệm bộ nhớ ảo; Demand Paging; Lỗi trang (Page Fault); Các thuật toán thay thế trang (Page Replacement Algorithms): FIFO, Optimal, LRU (Least Recently Used), Clock; Thrashing là gì?",
    "Tuan 12: He thong File I": "Tuần 12: Hệ thống File I",
    "Khai niem File va He thong File; Cac thuoc tinh file; Cac phep toan file; Cau truc thu muc: Don cap, Hai cap, Thu muc cay, Thu muc do thi; Phan quyen file (Unix permissions: rwx); Hard link va Symbolic link; inodes trong Linux ext4.": "Khái niệm File và Hệ thống File; Các thuộc tính file; Các phép toán file; Cấu trúc thư mục: Đơn cấp, Hai cấp, Thư mục cây, Thư mục đồ thị; Phân quyền file (Unix permissions: rwx); Hard link và Symbolic link; inodes trong Linux ext4.",
    "Tuan 13: He thong File II": "Tuần 13: Hệ thống File II",
    "Phuong phap cap phat khong gian dia: Lien tuc, Danh sach lien ket (FAT), Lap chi muc (ext2/ext3/ext4); Quan ly khong gian trong (Free-space management).": "Phương pháp cấp phát không gian đĩa: Liên tục, Danh sách liên kết (FAT), Lập chỉ mục (ext2/ext3/ext4); Quản lý không gian trống (Free-space management).",
    "Tuan 14: He thong Luu tru thu cap (I/O & Disk)": "Tuần 14: Hệ thống Lưu trữ thứ cấp (I/O & Disk)",
    "Cau truc dia tu (HDD), SSD; Thuat toan lap lich dia (Disk Scheduling): FCFS, SSTF, SCAN, C-SCAN, LOOK, C-LOOK; RAID (0, 1, 5, 6) va tinh du phong.": "Cấu trúc đĩa từ (HDD), SSD; Thuật toán lập lịch đĩa (Disk Scheduling): FCFS, SSTF, SCAN, C-SCAN, LOOK, C-LOOK; RAID (0, 1, 5, 6) và tính dự phòng.",

    # Network
    "Mon hoc gioi thieu ve kien truc mang Internet, mo hinh OSI va TCP/IP. Sinh vien hoc chi tiet cac giao thuc": "Môn học giới thiệu về kiến trúc mạng Internet, mô hình OSI và TCP/IP. Sinh viên học chi tiết các giao thức",
    "HTTP, DNS, TCP, UDP, IP, va cac thuat toan dinh tuyen, ky thuat chuyen mach.": "HTTP, DNS, TCP, UDP, IP, và các thuật toán định tuyến, kỹ thuật chuyển mạch.",
    "Tuan 1: Tong quan Mang May tinh va Internet": "Tuần 1: Tổng quan Mạng Máy tính và Internet",
    "Internet la gi? Thiet bi dau cuoi (Host), Router, Link; Mo hinh Client-Server va P2P; Chuyen mach goi (Packet Switching) vs Chuyen mach kenh (Circuit Switching); Do tre (Delay) va Mat goi (Loss); Mo hinh OSI 7 tang va Mo hinh TCP/IP 5 tang.": "Internet là gì? Thiết bị đầu cuối (Host), Router, Link; Mô hình Client-Server và P2P; Chuyển mạch gói (Packet Switching) vs Chuyển mạch kênh (Circuit Switching); Độ trễ (Delay) và Mất gói (Loss); Mô hình OSI 7 tầng và Mô hình TCP/IP 5 tầng.",
    "Tuan 2: Tang Ung dung (Application Layer) I": "Tuần 2: Tầng Ứng dụng (Application Layer) I",
    "Nguyen ly hoat dong cua tang ung dung; HTTP (HyperText Transfer Protocol): Request/Response, persistent/non-persistent, Cookies, Web Caching (Proxy server); HTTPS gioi thieu.": "Nguyên lý hoạt động của tầng ứng dụng; HTTP (HyperText Transfer Protocol): Request/Response, persistent/non-persistent, Cookies, Web Caching (Proxy server); HTTPS giới thiệu.",
    "Tuan 3: Tang Ung dung II": "Tuần 3: Tầng Ứng dụng II",
    "DNS (Domain Name System): Phap phan giai ten mien, Hierarchy cua DNS servers; FTP; SMTP, POP3, IMAP (Email); Kien truc Peer-to-Peer (BitTorrent).": "DNS (Domain Name System): Phép phân giải tên miền, Hierarchy của DNS servers; FTP; SMTP, POP3, IMAP (Email); Kiến trúc Peer-to-Peer (BitTorrent).",
    "Tuan 4: Tang Giao van (Transport Layer) - UDP": "Tuần 4: Tầng Giao vận (Transport Layer) - UDP",
    "Vai tro cua tang giao van: Multiplexing va Demultiplexing; Socket va Port number; UDP (User Datagram Protocol): Khong tin cay, khong ket noi, Checksum; Ung dung dung UDP (DNS, Video streaming).": "Vai trò của tầng giao vận: Multiplexing và Demultiplexing; Socket và Port number; UDP (User Datagram Protocol): Không tin cậy, không kết nối, Checksum; Ứng dụng dùng UDP (DNS, Video streaming).",
    "Tuan 5: Tang Giao van - TCP": "Tuần 5: Tầng Giao vận - TCP",
    "TCP (Transmission Control Protocol): Tin cay, huong ket noi; TCP Segment; 3-way handshake; Reliable Data Transfer (RDT) nguyen ly: ACK, NAK, Sequence Number, Timer; Go-Back-N va Selective Repeat.": "TCP (Transmission Control Protocol): Tin cậy, hướng kết nối; TCP Segment; 3-way handshake; Reliable Data Transfer (RDT) nguyên lý: ACK, NAK, Sequence Number, Timer; Go-Back-N và Selective Repeat.",
    "Tuan 6: TCP Congestion Control": "Tuần 6: TCP Congestion Control",
    "Kiem soat tac nghen (Congestion Control) vs Kiem soat luong (Flow Control); Thuat toan TCP Congestion Control: Slow Start, Congestion Avoidance, Fast Retransmit, Fast Recovery.": "Kiểm soát tắc nghẽn (Congestion Control) vs Kiểm soát luồng (Flow Control); Thuật toán TCP Congestion Control: Slow Start, Congestion Avoidance, Fast Retransmit, Fast Recovery.",
    "Tuan 7: Tang Mang (Network Layer) - Data Plane": "Tuần 7: Tầng Mạng (Network Layer) - Data Plane",
    "Vai tro cua Router; Data plane vs Control plane; Chuyen tiep (Forwarding); IP Protocol: IPv4 format, Dia chi IPv4, Subnet Mask, CIDR; DHCP (Dynamic Host Configuration Protocol); NAT (Network Address Translation).": "Vai trò của Router; Data plane vs Control plane; Chuyển tiếp (Forwarding); IP Protocol: IPv4 format, Địa chỉ IPv4, Subnet Mask, CIDR; DHCP (Dynamic Host Configuration Protocol); NAT (Network Address Translation).",
    "OSI, App Layer, UDP, TCP, IPv4.": "OSI, App Layer, UDP, TCP, IPv4.",
    "Thi TN va tu luan 60 phut": "Thi TN và tự luận 60 phút",
    "Tuan 9: Tang Mang - IPv6 va Control Plane": "Tuần 9: Tầng Mạng - IPv6 và Control Plane",
    "Ly do chuyen sang IPv6; Format IPv6; ICMP; Control Plane: Routing algorithms.": "Lý do chuyển sang IPv6; Format IPv6; ICMP; Control Plane: Routing algorithms.",
    "Tuan 10: Thuat toan Dinh tuyen (Routing)": "Tuần 10: Thuật toán Định tuyến (Routing)",
    "Link-State Routing Algorithm (Dijkstra); Distance-Vector Routing Algorithm (Bellman-Ford); OSPF (Open Shortest Path First) trong cung AS; BGP (Border Gateway Protocol) giua cac AS.": "Link-State Routing Algorithm (Dijkstra); Distance-Vector Routing Algorithm (Bellman-Ford); OSPF (Open Shortest Path First) trong cùng AS; BGP (Border Gateway Protocol) giữa các AS.",
    "Tuan 11: Tang Lien ket (Data Link Layer) I": "Tuần 11: Tầng Liên kết (Data Link Layer) I",
    "Chuc nang tang Link; Phat hien va sua loi (Parity, Checksum, CRC); Multiple Access Protocols: CSMA, CSMA/CD (Ethernet), CSMA/CA (WiFi); Dia chi MAC va ARP (Address Resolution Protocol).": "Chức năng tầng Link; Phát hiện và sửa lỗi (Parity, Checksum, CRC); Multiple Access Protocols: CSMA, CSMA/CD (Ethernet), CSMA/CA (WiFi); Địa chỉ MAC và ARP (Address Resolution Protocol).",
    "Tuan 12: Tang Lien ket II - Ethernet va Switch": "Tuần 12: Tầng Liên kết II - Ethernet và Switch",
    "Ethernet Frame; Hub vs Switch; Switch learning bang dia chi MAC; VLAN (Virtual LAN) co ban.": "Ethernet Frame; Hub vs Switch; Switch learning bảng địa chỉ MAC; VLAN (Virtual LAN) cơ bản.",
    "Tuan 13: Mang Khong day va Di dong (Wireless & Mobile)": "Tuần 13: Mạng Không dây và Di động (Wireless & Mobile)",
    "Dac diem mang khong day; WiFi (802.11): CSMA/CA, Hidden terminal problem; Bluetooth; Cellular networks (4G/5G) tong quan; Mobility: Mobile IP.": "Đặc điểm mạng không dây; WiFi (802.11): CSMA/CA, Hidden terminal problem; Bluetooth; Cellular networks (4G/5G) tổng quan; Mobility: Mobile IP.",
    "Tuan 14: An ninh Mang (Network Security)": "Tuần 14: An ninh Mạng (Network Security)",
    "Ma hoa doi xung va bat doi xung (RSA); Hashing; Chu ky so; Tong quan ve SSL/TLS (HTTPS); IPsec va VPN; Tuong lua (Firewall) va IDS/IPS.": "Mã hóa đối xứng và bất đối xứng (RSA); Hashing; Chữ ký số; Tổng quan về SSL/TLS (HTTPS); IPsec và VPN; Tường lửa (Firewall) và IDS/IPS.",

    # Web
    "Mon hoc huong dan phat trien ung dung web full-stack hien dai.": "Môn học hướng dẫn phát triển ứng dụng web full-stack hiện đại.",
    "Frontend voi HTML, CSS, JavaScript (ES6+), ReactJS. Backend voi Node.js, Express va thao tac CSDL MongoDB.": "Frontend với HTML, CSS, JavaScript (ES6+), ReactJS. Backend với Node.js, Express và thao tác CSDL MongoDB.",
    "Tuan 1: Frontend co ban - HTML & CSS": "Tuần 1: Frontend cơ bản - HTML & CSS",
    "Cach Internet hoat dong; HTML5 Semantic tags; CSS3 co ban: Box model, Selectors; Layout voi Flexbox va CSS Grid; Responsive web design voi Media Queries; Gioi thieu framework CSS (TailwindCSS/Bootstrap).": "Cách Internet hoạt động; HTML5 Semantic tags; CSS3 cơ bản: Box model, Selectors; Layout với Flexbox và CSS Grid; Responsive web design với Media Queries; Giới thiệu framework CSS (TailwindCSS/Bootstrap).",
    "Tuan 2: JavaScript co ban": "Tuần 2: JavaScript cơ bản",
    "Bien (var, let, const), Kieu du lieu, Cau truc dieu khien; Ham (Functions & Arrow Functions); DOM Manipulation (thao tac DOM bang JS thuần); Event Handling.": "Biến (var, let, const), Kiểu dữ liệu, Cấu trúc điều khiển; Hàm (Functions & Arrow Functions); DOM Manipulation (thao tác DOM bằng JS thuần); Event Handling.",
    "Tuan 3: JavaScript nang cao (ES6+)": "Tuần 3: JavaScript nâng cao (ES6+)",
    "Destructuring, Spread/Rest Operators; Template Literals; Array methods: map, filter, reduce; OOP trong JS (Classes); Asynchronous JS: Callbacks, Promises, async/await; Fetch API (Goi API REST).": "Destructuring, Spread/Rest Operators; Template Literals; Array methods: map, filter, reduce; OOP trong JS (Classes); Asynchronous JS: Callbacks, Promises, async/await; Fetch API (Gọi API REST).",
    "Tuan 4: ReactJS - Can ban": "Tuần 4: ReactJS - Căn bản",
    "Khai niem SPA (Single Page Application); Gioi thieu React, JSX; Components (Functional Components); Props de truyen du lieu; State (useState hook); Lifecycle va useEffect hook co ban.": "Khái niệm SPA (Single Page Application); Giới thiệu React, JSX; Components (Functional Components); Props để truyền dữ liệu; State (useState hook); Lifecycle và useEffect hook cơ bản.",
    "Tuan 5: ReactJS - Nang cao": "Tuần 5: ReactJS - Nâng cao",
    "Handling Events, Conditional Rendering, List & Keys; React Router (Routing trong SPA); Quan ly state phuc tap voi useReducer, Context API; Gioi thieu Redux Toolkit (Tuy chon).": "Handling Events, Conditional Rendering, List & Keys; React Router (Routing trong SPA); Quản lý state phức tạp với useReducer, Context API; Giới thiệu Redux Toolkit (Tùy chọn).",
    "Tuan 6: Backend co ban voi Node.js & Express": "Tuần 6: Backend cơ bản với Node.js & Express",
    "Kien truc Client-Server; Gioi thieu Node.js, npm, package.json; Xay dung server dau tien bang Express.js; Routing; Middleware trong Express; Cach xu ly HTTP GET/POST requests.": "Kiến trúc Client-Server; Giới thiệu Node.js, npm, package.json; Xây dựng server đầu tiên bằng Express.js; Routing; Middleware trong Express; Cách xử lý HTTP GET/POST requests.",
    "Tuan 7: RESTful API va JSON": "Tuần 7: RESTful API và JSON",
    "Thiet ke RESTful API: Resource, cac phuong thuc HTTP (GET, POST, PUT, PATCH, DELETE), Status Codes; Format JSON; Postman test API; CORS.": "Thiết kế RESTful API: Resource, các phương thức HTTP (GET, POST, PUT, PATCH, DELETE), Status Codes; Format JSON; Postman test API; CORS.",
    "HTML, CSS, JS, ReactJS, Node.js can ban.": "HTML, CSS, JS, ReactJS, Node.js căn bản.",
    "Thuc hanh tren may (React hoac Express)": "Thực hành trên máy (React hoặc Express)",
    "Tuan 9: Co so du lieu MongoDB (NoSQL)": "Tuần 9: Cơ sở dữ liệu MongoDB (NoSQL)",
    "MongoDB la gi? JSON/BSON document; Cai dat MongoDB Compass; CRUD thao tac co ban; Ket noi Node.js voi MongoDB qua thu vien Mongoose; Dinh nghia Schema, Model.": "MongoDB là gì? JSON/BSON document; Cài đặt MongoDB Compass; CRUD thao tác cơ bản; Kết nối Node.js với MongoDB qua thư viện Mongoose; Định nghĩa Schema, Model.",
    "Tuan 10: Ket hop Backend va Database": "Tuần 10: Kết hợp Backend và Database",
    "Xay dung hoan chinh CRUD RESTful API ket noi DB; Data Validation voi Joi/Mongoose; Xu ly quan he giua cac documents (Populate); Xu ly Error va tao Error Middleware chuẩn.": "Xây dựng hoàn chỉnh CRUD RESTful API kết nối DB; Data Validation với Joi/Mongoose; Xử lý quan hệ giữa các documents (Populate); Xử lý Error và tạo Error Middleware chuẩn.",
    "Tuan 11: Authentication va Authorization": "Tuần 11: Authentication và Authorization",
    "Session-based vs Token-based Authentication; Bam mat khau voi bcrypt; JSON Web Token (JWT); Dang nhap/Dang ky tai khoan; Tao Middleware bao ve cac route (Protect Routes).": "Session-based vs Token-based Authentication; Băm mật khẩu với bcrypt; JSON Web Token (JWT); Đăng nhập/Đăng ký tài khoản; Tạo Middleware bảo vệ các route (Protect Routes).",
    "Tuan 12: File Uploads va Tinh nang mo rong": "Tuần 12: File Uploads và Tính năng mở rộng",
    "Xu ly upload anh/file voi Multer; Luu tru anh local hoac Cloudinary; Ghi log voi Morgan; Gui email voi Nodemailer.": "Xử lý upload ảnh/file với Multer; Lưu trữ ảnh local hoặc Cloudinary; Ghi log với Morgan; Gửi email với Nodemailer.",
    "Tuan 13: Fullstack Integration (MERN)": "Tuần 13: Fullstack Integration (MERN)",
    "Ket noi ReactJS voi Backend (Axios); Luu token o Client (LocalStorage/HttpOnly Cookies); Xu ly state dang nhap cua User; Bao ve cac Route tren React (Private Route).": "Kết nối ReactJS với Backend (Axios); Lưu token ở Client (LocalStorage/HttpOnly Cookies); Xử lý state đăng nhập của User; Bảo vệ các Route trên React (Private Route).",
    "Tuan 14: Deployment (Trien khai)": "Tuần 14: Deployment (Triển khai)",
    "Dong goi Frontend va Backend; Trien khai Backend len Render/Heroku; Trien khai Frontend len Vercel/Netlify; Trien khai MongoDB len MongoDB Atlas; Cai dat bien moi truong (Environment Variables).": "Đóng gói Frontend và Backend; Triển khai Backend lên Render/Heroku; Triển khai Frontend lên Vercel/Netlify; Triển khai MongoDB lên MongoDB Atlas; Cài đặt biến môi trường (Environment Variables).",

    # KTPM
    "Mon hoc gioi thieu quy trinh ky thuat phan mem, tu khao sat yeu cau, thiet ke, den kiem thu.": "Môn học giới thiệu quy trình kỹ thuật phần mềm, từ khảo sát yêu cầu, thiết kế, đến kiểm thử.",
    "Tim hieu mo hinh Agile/Scrum va cac bieu do UML (Use-case, Class, Sequence).": "Tìm hiểu mô hình Agile/Scrum và các biểu đồ UML (Use-case, Class, Sequence).",
    "Tuan 1: Tong quan Ky thuat phan mem": "Tuần 1: Tổng quan Kỹ thuật phần mềm",
    "Phan mem la gi? Khung hoang phan mem; Ky thuat phan mem la gi?; Dac trung cua phan mem; Vong doi phat trien phan mem (SDLC).": "Phần mềm là gì? Khủng hoảng phần mềm; Kỹ thuật phần mềm là gì?; Đặc trưng của phần mềm; Vòng đời phát triển phần mềm (SDLC).",
    "Tuan 2: Cac mo hinh SDLC": "Tuần 2: Các mô hình SDLC",
    "Mo hinh Thac nuoc (Waterfall); Mo hinh V-shaped; Mo hinh Tang truong (Incremental); Mo hinh Xoan oc (Spiral); Gioi thieu Agile.": "Mô hình Thác nước (Waterfall); Mô hình V-shaped; Mô hình Tăng trưởng (Incremental); Mô hình Xoắn ốc (Spiral); Giới thiệu Agile.",
    "Tuan 3: Agile va Scrum Framework": "Tuần 3: Agile và Scrum Framework",
    "Tuyen ngon Agile; Scrum la gi?; Cac vai tro: Product Owner, Scrum Master, Development Team; Cac su kien: Sprint, Daily Scrum, Sprint Planning, Sprint Review, Sprint Retrospective; Artifacts: Product Backlog, Sprint Backlog.": "Tuyên ngôn Agile; Scrum là gì?; Các vai trò: Product Owner, Scrum Master, Development Team; Các sự kiện: Sprint, Daily Scrum, Sprint Planning, Sprint Review, Sprint Retrospective; Artifacts: Product Backlog, Sprint Backlog.",
    "Tuan 4: Ky thuat Yeu cau (Requirements Engineering)": "Tuần 4: Kỹ thuật Yêu cầu (Requirements Engineering)",
    "Yeu cau chuc nang (Functional Requirements) va phi chuc nang (Non-functional Requirements); Thu thap yeu cau (Phong van, Khao sat); Phan tich yeu cau; Tai lieu dac ta yeu cau phan mem (SRS).": "Yêu cầu chức năng (Functional Requirements) và phi chức năng (Non-functional Requirements); Thu thập yêu cầu (Phỏng vấn, Khảo sát); Phân tích yêu cầu; Tài liệu đặc tả yêu cầu phần mềm (SRS).",
    "Tuan 5: Mo hinh hoa yeu cau voi UML (Use Case)": "Tuần 5: Mô hình hóa yêu cầu với UML (Use Case)",
    "UML la gi?; Bieu do Use Case (Use Case Diagram); Tac nhan (Actor), Use Case, Quan he Include, Extend, Generalization; Cach viet dac ta Use Case chi tiet.": "UML là gì?; Biểu đồ Use Case (Use Case Diagram); Tác nhân (Actor), Use Case, Quan hệ Include, Extend, Generalization; Cách viết đặc tả Use Case chi tiết.",
    "Tuan 6: Bieu do Lop (Class Diagram)": "Tuần 6: Biểu đồ Lớp (Class Diagram)",
    "Xac dinh cac lop doi tuong tu bai toan; Thuoc tinh, Phuong thuc; Cac moi quan he giua cac lop: Association, Aggregation, Composition, Inheritance/Generalization.": "Xác định các lớp đối tượng từ bài toán; Thuộc tính, Phương thức; Các mối quan hệ giữa các lớp: Association, Aggregation, Composition, Inheritance/Generalization.",
    "Tuan 7: Bieu do Tuan tu va Bieu do Trang thai": "Tuần 7: Biểu đồ Tuần tự và Biểu đồ Trạng thái",
    "Bieu do Tuan tu (Sequence Diagram): Lifeline, Message, Synchronous, Asynchronous, Alt/Opt fragment; Bieu do Trang thai (State Machine Diagram): State, Transition, Event.": "Biểu đồ Tuần tự (Sequence Diagram): Lifeline, Message, Synchronous, Asynchronous, Alt/Opt fragment; Biểu đồ Trạng thái (State Machine Diagram): State, Transition, Event.",
    "SDLC, Scrum, UML Use Case, Class, Sequence.": "SDLC, Scrum, UML Use Case, Class, Sequence.",
    "Tu luan phan tich thiet ke he thong thuc te.": "Tự luận phân tích thiết kế hệ thống thực tế.",
    "Tuan 9: Kien truc Phan mem (Software Architecture)": "Tuần 9: Kiến trúc Phần mềm (Software Architecture)",
    "Kien truc phan mem la gi?; Mo hinh Client-Server; Mo hinh 3-layer (Presentation, Business, Data); Kien truc Microservices vs Monolithic; RESTful API kien truc.": "Kiến trúc phần mềm là gì?; Mô hình Client-Server; Mô hình 3-layer (Presentation, Business, Data); Kiến trúc Microservices vs Monolithic; RESTful API kiến trúc.",
    "Tuan 10: Thiet ke Giao dien nguoi dung (UI/UX)": "Tuần 10: Thiết kế Giao diện người dùng (UI/UX)",
    "Nguyen tac thiet ke UI (Don gian, Nhat quan, Phan hoi...); UX la gi?; Wireframing va Prototyping; Gioi thieu cong cu Figma; Tinh kha dung (Usability).": "Nguyên tắc thiết kế UI (Đơn giản, Nhất quán, Phản hồi...); UX là gì?; Wireframing và Prototyping; Giới thiệu công cụ Figma; Tính khả dụng (Usability).",
    "Tuan 11: Kiem thu Phan mem (Software Testing) I": "Tuần 11: Kiểm thử Phần mềm (Software Testing) I",
    "Muc tieu kiem thu; Black-box testing vs White-box testing; Cac cap do kiem thu: Unit Test, Integration Test, System Test, Acceptance Test (UAT).": "Mục tiêu kiểm thử; Black-box testing vs White-box testing; Các cấp độ kiểm thử: Unit Test, Integration Test, System Test, Acceptance Test (UAT).",
    "Tuan 12: Kiem thu Phan mem II": "Tuần 12: Kiểm thử Phần mềm II",
    "Ky thuat phan vach tuong duong, Phan tich gia tri bien; Viet Test Case; Bug va vong doi cua Bug; Test Automation vs Manual Testing.": "Kỹ thuật phân vạch tương đương, Phân tích giá trị biên; Viết Test Case; Bug và vòng đời của Bug; Test Automation vs Manual Testing.",
    "Tuan 13: Quan ly Du an Phan mem va GitHub": "Tuần 13: Quản lý Dự án Phần mềm và GitHub",
    "He thong quan ly phien ban (Git); Git Workflow co ban (Branch, Merge, Pull Request, Resolve Conflict); Uoc luong thoi gian (Story Points, Planning Poker); Quan ly source code tren GitHub.": "Hệ thống quản lý phiên bản (Git); Git Workflow cơ bản (Branch, Merge, Pull Request, Resolve Conflict); Ước lượng thời gian (Story Points, Planning Poker); Quản lý source code trên GitHub.",
    "Tuan 14: Bao tri va Phat trien sau trien khai": "Tuần 14: Bảo trì và Phát triển sau triển khai",
    "Bao tri phan mem (Sua loi, Thich ung, Hoan thien, Phong ngua); DevOps (CI/CD) co ban; Docker gioi thieu nhanh; Code Refactoring.": "Bảo trì phần mềm (Sửa lỗi, Thích ứng, Hoàn thiện, Phòng ngừa); DevOps (CI/CD) cơ bản; Docker giới thiệu nhanh; Code Refactoring.",

    # AI
    "Mon hoc gioi thieu nen tang ly thuyet va ung dung thuc te cua Tri tue Nhan tao, tu AI co dien den Hoc may hien dai.": "Môn học giới thiệu nền tảng lý thuyết và ứng dụng thực tế của Trí tuệ Nhân tạo, từ AI cổ điển đến Học máy hiện đại.",
    "Sinh vien thuc hanh voi Python, scikit-learn, TensorFlow/Keras va Google Colab.": "Sinh viên thực hành với Python, scikit-learn, TensorFlow/Keras và Google Colab.",
    "Tuan 1: Tong quan Tri tue Nhan tao": "Tuần 1: Tổng quan Trí tuệ Nhân tạo",
    "AI la gi? Lich su AI (1956 den nay); Phan loai AI: Narrow AI (ANI), General AI (AGI), Superintelligence; Turing Test; Cac ung dung AI thuc te: Xe tu lai, NLP, Y te, Tai chinh; Tac dong AI den xa hoi; Dao duc trong AI (AI Ethics); Gioi thieu Python va Jupyter Notebook.": "AI là gì? Lịch sử AI (1956 đến nay); Phân loại AI: Narrow AI (ANI), General AI (AGI), Superintelligence; Turing Test; Các ứng dụng AI thực tế: Xe tự lái, NLP, Y tế, Tài chính; Tác động AI đến xã hội; Đạo đức trong AI (AI Ethics); Giới thiệu Python và Jupyter Notebook.",
    "Tuan 2: Bai toan Tim kiem khong co tri thuc": "Tuần 2: Bài toán Tìm kiếm không có tri thức",
    "Khai niem Khong gian trang thai (State Space); Cay tim kiem; BFS (Breadth-First Search): Hoan toan, Toi uu voi trong so bang nhau; DFS (Depth-First Search): Uu nhuoc diem; Iterative Deepening DFS (IDDFS); Uniform Cost Search; Bai toan: Di chuyen tu A-B, 8-puzzle, Bai toan 8 hau.": "Khái niệm Không gian trạng thái (State Space); Cây tìm kiếm; BFS (Breadth-First Search): Hoàn toàn, Tối ưu với trọng số bằng nhau; DFS (Depth-First Search): Ưu nhược điểm; Iterative Deepening DFS (IDDFS); Uniform Cost Search; Bài toán: Di chuyển từ A-B, 8-puzzle, Bài toán 8 hậu.",
    "Tuan 3: Tim kiem co Tri thuc (Informed Search)": "Tuần 3: Tìm kiếm có Tri thức (Informed Search)",
    "Heuristic Function h(n) va do chinh xac; Greedy Best-First Search; A* Search: f(n) = g(n) + h(n), Admissible heuristic, Consistent heuristic; IDA*; Memory-Bounded: RBFS, SMA*; Bai toan: Tim duong tren ban do, Rubik\\'s Cube.": "Heuristic Function h(n) và độ chính xác; Greedy Best-First Search; A* Search: f(n) = g(n) + h(n), Admissible heuristic, Consistent heuristic; IDA*; Memory-Bounded: RBFS, SMA*; Bài toán: Tìm đường trên bản đồ, Rubik\\'s Cube.",
    "Tuan 4: Tim kiem trong moi truong Doi khang": "Tuần 4: Tìm kiếm trong môi trường Đối kháng",
    "Bai toan tro choi (Game) 2 nguoi; Cay Minimax; Alpha-Beta Pruning: Giam xet nhieu nut; Depth-limited Minimax; Expectimax (moi truong ngau nhien); Monte Carlo Tree Search (MCTS); Ung dung: Co vua, Co tuong, Co tung, AlphaGo/AlphaZero gioi thieu.": "Bài toán trò chơi (Game) 2 người; Cây Minimax; Alpha-Beta Pruning: Giảm xét nhiều nút; Depth-limited Minimax; Expectimax (môi trường ngẫu nhiên); Monte Carlo Tree Search (MCTS); Ứng dụng: Cờ vua, Cờ tướng, Cờ túng, AlphaGo/AlphaZero giới thiệu.",
    "Tuan 5: CSP – Bai toan Rang buoc": "Tuần 5: CSP – Bài toán Ràng buộc",
    "Constraint Satisfaction Problem: Bien, Mien, Rang buoc; Arc Consistency (AC-3); Backtracking co cai tien (MRV, Degree Heuristic, LCV, Forward Checking); Bai toan: Dien so, To mau ban do, Xep lich thi; Gioi thieu constraint propagation.": "Constraint Satisfaction Problem: Biến, Miền, Ràng buộc; Arc Consistency (AC-3); Backtracking có cải tiến (MRV, Degree Heuristic, LCV, Forward Checking); Bài toán: Điền số, Tô màu bản đồ, Xếp lịch thi; Giới thiệu constraint propagation.",
    "Tuan 6: Bieu dien Tri thuc va Suy luan": "Tuần 6: Biểu diễn Tri thức và Suy luận",
    "Logic menh de va logic vi tu (on tap); Chuong trinh logic (Logic Programming); Mang ngu nghia (Semantic Network); Frame; Ontology (OWL); Rule-based Systems; Forward Chaining va Backward Chaining; Prolog co ban: Fact, Rule, Query.": "Logic mệnh đề và logic vị từ (ôn tập); Chương trình logic (Logic Programming); Mạng ngữ nghĩa (Semantic Network); Frame; Ontology (OWL); Rule-based Systems; Forward Chaining và Backward Chaining; Prolog cơ bản: Fact, Rule, Query.",
    "Tuan 7: He chuyen gia (Expert System)": "Tuần 7: Hệ chuyên gia (Expert System)",
    "Khai niem He chuyen gia; Co so tri thuc (Knowledge Base); Co che suy dien (Inference Engine); MYCIN, DENDRAL (lich su); Xay dung He chuyen gia don gian bang Python: Chan doan benh don gian, Tu van mua xe; Uu va nhuoc diem cua He chuyen gia.": "Khái niệm Hệ chuyên gia; Cơ sở tri thức (Knowledge Base); Cơ chế suy diễn (Inference Engine); MYCIN, DENDRAL (lịch sử); Xây dựng Hệ chuyên gia đơn giản bằng Python: Chẩn đoán bệnh đơn giản, Tư vấn mua xe; Ưu và nhược điểm của Hệ chuyên gia.",
    "Tuan 8: KIEM TRA GIUA KY – Phan AI Co dien": "Tuần 8: KIỂM TRA GIỮA KỲ – Phần AI Cổ điển",
    "Tim kiem (BFS/DFS/A*), Minimax, CSP, Bieu dien tri thuc, He chuyen gia.": "Tìm kiếm (BFS/DFS/A*), Minimax, CSP, Biểu diễn tri thức, Hệ chuyên gia.",
    "Tu luan tren giay 90 phut: Phan tich va ve cay tim kiem, viet gia code.": "Tự luận trên giấy 90 phút: Phân tích và vẽ cây tìm kiếm, viết giả code.",
    "Tuan 9: Hoc may I – Co so va Hoi quy tuyen tinh": "Tuần 9: Học máy I – Cơ sở và Hồi quy tuyến tính",
    "Hoc co giam sat, khong giam sat, tang cuong; Features, Labels, Dataset, Train/Val/Test Split; Linear Regression: Ham mat mat (MSE), Gradient Descent, Learning Rate, Overfitting vs Underfitting; Regularization: L1 (Lasso), L2 (Ridge); Polynomial Regression; scikit-learn API.": "Học có giám sát, không giám sát, tăng cường; Features, Labels, Dataset, Train/Val/Test Split; Linear Regression: Hàm mất mát (MSE), Gradient Descent, Learning Rate, Overfitting vs Underfitting; Regularization: L1 (Lasso), L2 (Ridge); Polynomial Regression; scikit-learn API.",
    "Tuan 10: Hoc may II – Phan loai co giam sat": "Tuần 10: Học máy II – Phân loại có giám sát",
    "Logistic Regression: Sigmoid function, Binary/Multinomial Classification, Log Loss; Decision Tree: Entropy, Information Gain, Gini Index, Pruning; Random Forest: Bagging, Feature Importance; k-NN (k-Nearest Neighbors); Naive Bayes; Support Vector Machine (SVM): Kernel Trick, C parameter; Danh gia: Accuracy, Precision, Recall, F1-Score, ROC-AUC.": "Logistic Regression: Sigmoid function, Binary/Multinomial Classification, Log Loss; Decision Tree: Entropy, Information Gain, Gini Index, Pruning; Random Forest: Bagging, Feature Importance; k-NN (k-Nearest Neighbors); Naive Bayes; Support Vector Machine (SVM): Kernel Trick, C parameter; Đánh giá: Accuracy, Precision, Recall, F1-Score, ROC-AUC.",
    "Tuan 11: Hoc khong giam sat va Giam chieu": "Tuần 11: Học không giám sát và Giảm chiều",
    "K-Means Clustering: Thuat toan, Elbow Method chon K; Hierarchical Clustering: Dendrogram; DBSCAN: Xu ly nhieu; Gaussian Mixture Model (GMM); PCA (Principal Component Analysis): Eigenvalue, Eigenvector, Explained Variance; t-SNE va UMAP thi giac hoa; Danh gia Clustering: Silhouette Score.": "K-Means Clustering: Thuật toán, Elbow Method chọn K; Hierarchical Clustering: Dendrogram; DBSCAN: Xử lý nhiễu; Gaussian Mixture Model (GMM); PCA (Principal Component Analysis): Eigenvalue, Eigenvector, Explained Variance; t-SNE và UMAP thị giác hóa; Đánh giá Clustering: Silhouette Score.",
    "Tuan 12: Mang no-ron nhan tao (ANN)": "Tuần 12: Mạng nơ-ron nhân tạo (ANN)",
    "Perceptron: Dau vao, Trong so, Bias, Ham kich hoat; Multilayer Perceptron (MLP): An tang; Backpropagation: Tinh dao ham, Cap nhat trong so; Ham kich hoat: ReLU, Sigmoid, Tanh, Softmax; Adam Optimizer; Batch Normalization; Dropout; Keras/TensorFlow: Xay dung MLP phan loai MNIST.": "Perceptron: Đầu vào, Trọng số, Bias, Hàm kích hoạt; Multilayer Perceptron (MLP): Ẩn tầng; Backpropagation: Tính đạo hàm, Cập nhật trọng số; Hàm kích hoạt: ReLU, Sigmoid, Tanh, Softmax; Adam Optimizer; Batch Normalization; Dropout; Keras/TensorFlow: Xây dựng MLP phân loại MNIST.",
    "Tuan 13: Hoc sau (Deep Learning) – CNN va RNN": "Tuần 13: Học sâu (Deep Learning) – CNN và RNN",
    "Convolutional Neural Network (CNN): Convolution Layer, Pooling, Flatten, Dense; Kien truc: LeNet, VGG, ResNet (gioi thieu); Ung dung: Phan loai anh, Object Detection; Recurrent Neural Network (RNN): Bieu dien chuoi; LSTM: Cell State, Forget/Input/Output Gate; Ung dung: Phan tich cam xuc (Sentiment Analysis), Du doan chuoi thoi gian.": "Convolutional Neural Network (CNN): Convolution Layer, Pooling, Flatten, Dense; Kiến trúc: LeNet, VGG, ResNet (giới thiệu); Ứng dụng: Phân loại ảnh, Object Detection; Recurrent Neural Network (RNN): Biểu diễn chuỗi; LSTM: Cell State, Forget/Input/Output Gate; Ứng dụng: Phân tích cảm xúc (Sentiment Analysis), Dự đoán chuỗi thời gian.",
    "Tuan 14: Xu ly Ngon ngu Tu nhien (NLP)": "Tuần 14: Xử lý Ngôn ngữ Tự nhiên (NLP)",
    "Tokenization, Stop words, Stemming, Lemmatization; TF-IDF: Tim kiem van ban; Word Embedding: Word2Vec (CBOW, Skip-gram), GloVe; Transformer Architecture: Self-Attention, Multi-head Attention; BERT gioi thieu; Ung dung: Chatbot, Dich thuat, Tom tat van ban; Demo ChatGPT API.": "Tokenization, Stop words, Stemming, Lemmatization; TF-IDF: Tìm kiếm văn bản; Word Embedding: Word2Vec (CBOW, Skip-gram), GloVe; Transformer Architecture: Self-Attention, Multi-head Attention; BERT giới thiệu; Ứng dụng: Chatbot, Dịch thuật, Tóm tắt văn bản; Demo ChatGPT API.",
    "Tuan 15: THI CUOI KY – Du an Machine Learning": "Tuần 15: THI CUỐI KỲ – Dự án Machine Learning",
    "Bao ve du an nhom (2-3 nguoi): Xay dung mo hinh ML/DL giai quyet bai toan thuc te; Demo Jupyter Notebook, Phan tich ket qua, Do chinh xac, Dataset su dung.": "Bảo vệ dự án nhóm (2-3 người): Xây dựng mô hình ML/DL giải quyết bài toán thực tế; Demo Jupyter Notebook, Phân tích kết quả, Độ chính xác, Dataset sử dụng.",
    "Thi viet: 90 phut tu luan: Phan tich mo hinh, Chon giai thuat, Danh gia.": "Thi viết: 90 phút tự luận: Phân tích mô hình, Chọn giải thuật, Đánh giá.",
    "Nop GitHub repo + Bao cao PDF.": "Nộp GitHub repo + Báo cáo PDF.",

    # Generic remaining week numbers if needed, they are already handled by substrings above
}

# Perform replacement
for old, new in replacements.items():
    content = content.replace(old, new)

with open('/home/lib/oer_chatbot_project/TLCN_OER_Lakehouse/scripts/moodle_seed_data.php', 'w', encoding='utf-8') as f:
    f.write(content)

print("Accents added.")
